import compiler.NativeImage

plugins {
  id 'compiler.native-image'
  id 'com.gradleup.shadow' version '8.3.6'
  id 'com.palantir.git-version' version '1.0.0'
}

apply plugin: 'scala'
apply plugin: 'application'

repositories {
    mavenCentral()
}

ext {
    scala_maj = '3'
    scala_ver = "${scala_maj}.9.0"
}

dependencies {
    implementation "org.scala-lang:scala3-library_${scala_maj}:${scala_ver}"
    implementation "org.scala-lang:scala3-compiler_${scala_maj}:${scala_ver}"

    testImplementation "org.scalatest:scalatest_${scala_maj}:3.2.20"
    testImplementation "org.scalactic:scalactic_${scala_maj}:3.2.20"

    testImplementation 'junit:junit:4.13.2'
    testImplementation "org.scalatestplus:junit-4-13_${scala_maj}:3.2.20.0"
}

version = gitVersion()

application {
    mainClass.set('cdb.dump')
}

processResources {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE // allow duplicates
}

sourceSets {
    main {
        scala {
            srcDir 'src/main'
        }
        resources {
            srcDir 'src/main/resources'
            exclude '**/*.sample'
        }
    }
}

test {
    testLogging.showStandardStreams = true
    testLogging.exceptionFormat = 'full'
    minHeapSize = '2g'
    maxHeapSize = '6g'
}

task repl(type:JavaExec) {
    mainClass = 'scala.tools.nsc.MainGenericRunner'
    classpath = sourceSets.main.runtimeClasspath
    standardInput = System.in
    args '-usejavacp'
}

compileScala {
    scalaCompileOptions.additionalParameters = [
        '-feature'
      , '-Werror'
      , '-release'
      , '17'
    ]
}

shadowJar {
    manifest {
        attributes 'App-Version': version
    }
}

nativeImage {
    dependsOn shadowJar

    minHeap = 1
    maxHeap = 3
    maxNew = 3

    parameters = [
      NativeImage.Option.STATIC
    , NativeImage.Option.MUSL
    , NativeImage.Option.LINK_BUILD
    ]
}
